#ifndef SYSTEM_INFO_ERRORS_H
#define SYSTEM_INFO_ERRORS_H

typedef enum
{
    OK = 0,
    ERROR = 1,
    CPU_READ_ERROR = 2,
    CPU_INVALID_ERROR = 3,
    RAM_ERROR = 4,
    NETWORK_ERROR = 5,
    UPTIME_ERROR = 6,
    ERR_UBUS_CONNECT = 7,
    ERR_UBUS_SYSTEM_LOOKUP = 8,
    ERR_UBUS_LAN_LOOKUP = 9,
    ERR_UBUS_WAN_LOOKUP = 10,
    ERR_UBUS_INVOKE = 11,
    ERR_UBUS_NOT_INITIALIZED = 12

} Error_Code;

#endif
