#ifndef SYSTEM_INFO_ERRORS_H
#define SYSTEM_INFO_ERRORS_H

typedef enum
{
    OK,
    ERROR,
    CPU_READ_ERROR,
    CPU_INVALID_ERROR,
    RAM_ERROR,
    NETWORK_ERROR,
    UPTIME_ERROR,
    ERR_UBUS_CONNECT,
    ERR_UBUS_SYSTEM_LOOKUP,
    ERR_UBUS_LAN_LOOKUP,
    ERR_UBUS_WAN_LOOKUP,
    ERR_UBUS_NETWORK_DEVICE_LOOKUP,
    ERR_UBUS_INVOKE,
    ERR_UBUS_NOT_INITIALIZED

} Error_Code;

#endif
